<a href="https://colab.research.google.com/github/Althaf0097/Demo/blob/main/Second.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
height =[161,182,161,154,176,170,167,171,170,174]
weight =[72,80,60,56,78,68,72,78,72,77]
list1 =[]
for x,y in zip(height,weight):
  list1.append(y/(x**2))
print(list1)

[0.0027776706145596236, 0.0024151672503320855, 0.0023147255121330197, 0.0023612750885478157, 0.002518078512396694, 0.002352941176470588, 0.0025816630212628635, 0.002667487432030368, 0.002491349480968858, 0.002543268595587264]


In [ ]:
! pip install numpy


# NUMPY LIBRARY

In [ ]:
import numpy as np
height = [161,182,161,154,176,170,167,171,170,174]
weight = [72,80,60,56,78,68,72,78,72,77]
x = np.array(height)
y = np.array(weight)
BMI = np.array(y/x**2)
print(BMI)

[0.00277767 0.00241517 0.00231473 0.00236128 0.00251808 0.00235294
 0.00258166 0.00266749 0.00249135 0.00254327]


In [ ]:
arr_2d = np.array([[1,2,3,5],[4,5,6,7],[7,8,9,8]])
print(arr_2d)

[[1 2 3 5]
 [4 5 6 7]
 [7 8 9 8]]


In [ ]:
arr_2d.ndim

2

In [ ]:
arr_2d.shape

(3, 4)

In [ ]:
arr_2d.size

12

In [ ]:
arr_2d.dtype

dtype('int64')

In [ ]:
arr_2d.itemsize

8

In [ ]:
ran_arr = np.arange(0,16)
ran_arr.reshape(4,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
ran_arr.max()

15

In [ ]:
np.min(ran_arr)

0

In [ ]:
np.mean(ran_arr)

7.5

In [ ]:
np.median(ran_arr)

7.5

In [ ]:
np.std(ran_arr)

4.6097722286464435

In [ ]:
np.var(ran_arr)

21.25

In [ ]:
np.sum(ran_arr)

120

In [ ]:
np.sort(ran_arr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
arr_zero = np.zeros((3,3))
print(arr_zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr_zr = np.zeros((4,4),dtype = int)
print(arr_zr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
arr_one = np.ones((3,3),dtype = int)
print(arr_one)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
arr_iden = np.identity(3,dtype = int)
print(arr_iden)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
np.eye(4,4,1,dtype = int)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [ ]:
x = np.random.randint(1,100,5)
print(x)

[78 65 34 38 48]


In [ ]:
x[1],x[4],x[-2]

(65, 48, 38)

In [ ]:
y = np.array([0,2,4,6,8,10,12,14])

In [ ]:
y

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [ ]:
y[4]

8

In [ ]:
y[0:3] = 100

In [ ]:
y>10


array([ True,  True,  True, False, False, False,  True,  True])

In [ ]:
c = y>10
c

array([ True,  True,  True, False, False, False,  True,  True])

In [ ]:
y[c]

array([100, 100, 100,  12,  14])

# ***`pandas`***

In [ ]:
import pandas as pd

In [ ]:
li = pd.Series([1,2,3,4,5])
print(li)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
li.values

array([1, 2, 3, 4, 5])

In [ ]:
li.max()

5

In [ ]:
li.min()

1

In [ ]:
li.mean()

3.0

In [ ]:
li.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
li_series = pd.Series([34,21,35,40,55],index = ['a','b','c','d','e'])
pd.Series(li_series)

a    34
b    21
c    35
d    40
e    55
dtype: int64

In [ ]:
li_series['c']

35

In [ ]:
li_serie = pd.Series([34,21,35,'maniku',55],index = ['a','b','c','d','e'])
pd.Series(li_serie)

a        34
b        21
c        35
d    maniku
e        55
dtype: object

In [ ]:
li_serie['d']

'maniku'

In [ ]:
data = {'INDIA':5000,'CHINA':6000,'RUSSIA':7000,'JAPAN':8000}

pd.Series(data)

INDIA     5000
CHINA     6000
RUSSIA    7000
JAPAN     8000
dtype: int64

In [ ]:
data['INDIA']

5000

In [ ]:
city2 = pd.Series(['day1','day2','day3','day4'],index = [12,-6,8,-3])
city2

12    day1
-6     day2
 8     day3
-3     day4
dtype: object

In [ ]:
city2(city2.index>10)

TypeError: 'Series' object is not callable

In [ ]:
country = pd.Series(['INDIA','CHINA','RUSSIA','JAPAN','GERMANY'],index = [150,200,300,450,500])
pd.Series(country)

150      INDIA
200      CHINA
300     RUSSIA
450      JAPAN
500    GERMANY
dtype: object

In [ ]:
country[(country.index > 200) & (country.index > 400)]

country*2

150        INDIAINDIA
200        CHINACHINA
300      RUSSIARUSSIA
450        JAPANJAPAN
500    GERMANYGERMANY
dtype: object

In [ ]:
d1 = {'Kerala':28,'Andhra':25,'Delhi':38,'TN':31,'Karnataka':19}
pd.Series(d1)

Kerala       28
Andhra       25
Delhi        38
TN           31
Karnataka    19
dtype: int64

In [ ]:
state = {'Kerala','Andhra','Delhi','TN','MP','Karnataka'}
d1 = pd.Series(d1,index = state)
d1

Kerala       28.0
Karnataka    19.0
TN           31.0
Andhra       25.0
MP            NaN
Delhi        38.0
dtype: float64

# Data Frame

In [ ]:
data1 ={'Year':[2001,2002,2004,2005,2006],
        'states':['Kerala','Andhra','Delhi','TN','Karnataka'],
        'pop':[150,200,300,450,500]}

In [ ]:
df = pd.DataFrame(data1)
df

Year     states  pop
0  2001     Kerala  150
1  2002     Andhra  200
2  2004      Delhi  300
3  2005         TN  450
4  2006  Karnataka  500

In [ ]:
pop_data1 = pd.DataFrame(data1,columns = ['Year','states','pop','income'])
pop_data1

Year     states  pop income
0  2001     Kerala  150    NaN
1  2002     Andhra  200    NaN
2  2004      Delhi  300    NaN
3  2005         TN  450    NaN
4  2006  Karnataka  500    NaN

In [ ]:
pop_data1['states']

0       Kerala
1       Andhra
2        Delhi
3           TN
4    Karnataka
Name: states, dtype: object

In [ ]:
pop_data1['income'] = [1600,2330,3000,4500,5000]
pop_data1

Year     states  pop  income
0  2001     Kerala  150    1600
1  2002     Andhra  200    2330
2  2004      Delhi  300    3000
3  2005         TN  450    4500
4  2006  Karnataka  500    5000

In [ ]:
pop_data1['income']

0    1600
1    2330
2    3000
3    4500
4    5000
Name: income, dtype: int64

In [ ]:
pop_data1['dept'] = [150,250,200,450,490]
pop_data1

Year     states  pop  income  dept
0  2001     Kerala  150    1600   150
1  2002     Andhra  200    2330   250
2  2004      Delhi  300    3000   200
3  2005         TN  450    4500   450
4  2006  Karnataka  500    5000   490

In [ ]:
pop_data1 = pop_data1.drop('dept', axis=1)

In [ ]:
pop_data1

Year     states  pop  income
0  2001     Kerala  150    1600
1  2002     Andhra  200    2330
2  2004      Delhi  300    3000
3  2005         TN  450    4500
4  2006  Karnataka  500    5000

In [ ]:
import pandas as pd
dataset = pd.read_csv('titanic.csv')
dataset

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
dataset.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S